name: Deploy to Cloudflare Pages on tag from main

on:
  push:
    tags:
      - "*"
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tag commit is on main
        run: |
          git fetch origin main
          if ! git merge-base --is-ancestor HEAD origin/main; then
            echo "This tag is not from main. Aborting." >&2
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Create version.json from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION="${GITHUB_REF_NAME}"
          if ! [[ "$VERSION" =~ ^[0-9]+$ ]]; then
            echo "Tag name must be a number (e.g., 123). Got: $VERSION" >&2
            exit 1
          fi
          echo "{ \"version\": ${VERSION} }" > frontend/public/version.json
          echo "Wrote version.json:" && cat frontend/public/version.json

      - name: Copy environment file
        run: |
          ENV_FILE=$(find . -name "frontend_*.env" | head -1)
          if [ -n "$ENV_FILE" ]; then
            echo "Found environment file: $ENV_FILE"
            cp "$ENV_FILE" frontend/.env
            echo "Copied $ENV_FILE to frontend/.env"
          else
            echo "No frontend_*.env file found"
            exit 1
          fi

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        working-directory: frontend
        run: pnpm run build

      - name: Create Cloudflare Pages project if not exists
        run: |
          # Check if project exists
          PROJECT_NAME="${{ github.event.repository.name }}"
          ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}"
          
          # List existing projects
          EXISTING_PROJECTS=$(curl -s -X GET \
            "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/pages/projects" \
            -H "Authorization: Bearer ${API_TOKEN}" \
            -H "Content-Type: application/json")
          
          # Check if project exists
          if echo "$EXISTING_PROJECTS" | grep -q "\"name\":\"${PROJECT_NAME}\""; then
            echo "Project ${PROJECT_NAME} already exists"
          else
            echo "Creating new project: ${PROJECT_NAME}"
            curl -s -X POST \
              "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/pages/projects" \
              -H "Authorization: Bearer ${API_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{\"name\":\"${PROJECT_NAME}\",\"production_branch\":\"publish\"}"
            echo "Project created successfully"
          fi

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        id: pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ github.event.repository.name }}
          directory: frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Set production branch for publish, otherwise it's a preview
          productionBranch: publish

